version: '3'
services:
  rest-api:
    build: .
    expose: [ "8000:8000" ]
    ports: [ "8000:8000" ]
    depends_on: [ postgres ]
  postgres:
    image: postgres:12-alpine
    ports: [ "5432:5432" ]
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: users
