// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package sqlc

import ()

type User struct {
	ID          int64
	Name        string
	PhoneNumber string
	Country     string
	City        string
}
