name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: root
          POSTGRES_DB: users
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up Golang
        uses: actions/setup-go@v4
      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64 /usr/bin/migrate
      - name: Prepare PostgreSQL
        run: make migrateup
      - name: Run tests
        run: go test -coverprofile /dev/null ./...

  lint:
    name: GolangCI-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true

  SQLCCheck:
    name: SQLC checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Prepare SQLC
        uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: '1.19.1'
      - name: Check autogenerated code
        run: sqlc diff
      - name: Vet SQL related code
        run: sqlc vet
